# This is a basic workflow to help you get started with Actions

name: DEPLOY PROD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  #pull_request:
   # branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      - name: EMCI.COM EMCI.ORG

        #FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          protocol: ftps
          server: ${{ secrets.host }}
          username: ${{ secrets.username }}
          password: ${{ secrets.ftp_password }}
          port: 21
          local-dir: ./
          server-dir: /public_html/prod/
          log-level: minimal
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
            LICENSE