# This is a basic workflow to help you get started with Actions

name: DEPLOY PROD EMCI.COM

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  #pull_request:
   # branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      - name: DEPLOY

        #FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          protocol: ftps
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./
          server-dir: /public_html/emci.com/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
            LICENSE

        #SFTP
        # uses: wlixcc/SFTP-Deploy-Action@v1.0
        # with:
        #   username: 'emcitv@ministryrevealed.com'
        #   server: 'ftp.ministryrevealed.com'
        #   ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
        #   local_path: './'
        #   port: '21'
        #   remote_path: '/public_html/lib/'
        #   args: '-o ConnectTimeout=5'
        #   
        #   
        #   